#
# Build kernel
#

include Config.mk

OBJS		:=	src/config.o \
			src/control/control.o \
			src/control/mister.o \
			src/control/rotaryencoder.o \
			src/control/simplebuttons.o \
			src/control/simpleencoder.o \
			src/kernel.o \
			src/lcd/drivers/hd44780.o \
			src/lcd/drivers/hd44780fourbit.o \
			src/lcd/drivers/hd44780i2c.o \
			src/lcd/drivers/sh1106.o \
			src/lcd/drivers/ssd1306.o \
			src/lcd/ui.o \
			src/main.o \
			src/midimonitor.o \
			src/midiparser.o \
			src/mt32pi.o \
			src/net/applemidi.o \
			src/net/ftpdaemon.o \
			src/net/ftpworker.o \
			src/net/udpmidi.o \
			src/pisound.o \
			src/power.o \
			src/rommanager.o \
			src/soundfontmanager.o \
			src/synth/mt32synth.o \
			src/synth/nukedmt32synth.o \
			src/synth/soundfontsynth.o \
			src/synth/sc55synth.o  \
                        src/synth/sc88linkprobe.o \
			src/zoneallocator.o

EXTRACLEAN	+=	src/*.d src/*.o \
			src/control/*.d src/control/*.o \
			src/lcd/*.d src/lcd/*.o \
			src/lcd/drivers/*.d src/lcd/drivers/*.o \
			src/net/*.d src/net/*.o \
			src/synth/*.d src/synth/*.o

#
# inih
#
OBJS		+=	$(INIHHOME)/ini.o
INCLUDE		+=	-I $(INIHHOME)
EXTRACLEAN	+=	$(INIHHOME)/ini.d \
			$(INIHHOME)/ini.o

# Circle Step 51: allow Make to resolve bare header dependencies generated by dependency files
VPATH += $(CIRCLESTDLIBHOME)/include

INCLUDE		+=	-I$(CIRCLESTDLIBHOME)/include

include $(CIRCLEHOME)/Rules.mk

CFLAGS		+=	-Werror -Wextra -Wno-unused-parameter

CFLAGS		+=	-I "$(NEWLIBDIR)/include" \
			-I $(STDDEF_INCPATH) \
			-I$(CIRCLESTDLIBHOME)/include \
			-I include \
			-I .

CPPFLAGS	+=	-I"$(NEWLIBDIR)/include" \
			-I$(STDDEF_INCPATH) \
			-I$(CIRCLESTDLIBHOME)/include \
			-Iinclude \
			-I.

LIBS 		:=	$(CIRCLE_STDLIB_LIBS) \
			$(CIRCLEHOME)/addon/fatfs/libfatfs.a \
			$(CIRCLEHOME)/addon/SDCard/libsdcard.a \
			$(CIRCLEHOME)/addon/wlan/hostap/wpa_supplicant/libwpa_supplicant.a \
			$(CIRCLEHOME)/addon/wlan/libwlan.a \
			$(CIRCLEHOME)/lib/fs/libfs.a \
			$(CIRCLEHOME)/lib/input/libinput.a \
			$(CIRCLEHOME)/lib/libcircle.a \
			$(CIRCLEHOME)/lib/net/libnet.a \
			$(CIRCLEHOME)/lib/sched/libsched.a \
			$(CIRCLEHOME)/lib/sound/libsound.a \
			$(CIRCLEHOME)/lib/usb/libusb.a

ifeq ($(HDMI_CONSOLE), 1)
DEFINE		+=	-D HDMI_CONSOLE
endif

-include $(DEPS)

INCLUDE		+=	-I $(MT32EMUBUILDDIR)/include \
			-I $(MT32EMUHOME)/src/srchelper/srctools/include
EXTRALIBS	+=	$(MT32EMULIB)

# Experimental Nuked-MT32 bare-metal core
DEFINE		+=	-DNUKED_MT32_BAREMETAL
INCLUDE		+=	-I $(NUKEDMT32HOME) \
			-I $(NUKEDMT32HOME)/munt
EXTRALIBS	+=	--whole-archive $(NUKEDMT32LIB) --no-whole-archive

INCLUDE		+=	-I $(FLUIDSYNTHBUILDDIR)/include \
			-I $(FLUIDSYNTHHOME)/include
EXTRALIBS	+=	$(FLUIDSYNTHLIB)

#
# Generate version string from git tag
#
VERSION=$(shell git describe --tags --dirty --always 2>/dev/null)
ifneq ($(VERSION),)
DEFINE		+=	-D MT32_PI_VERSION=\"$(VERSION)\"
endif

# Circle Step 51: include paths for C++ compilation
CXXFLAGS        +=      -I"$(NEWLIBDIR)/include" \
                        -I$(STDDEF_INCPATH) \
                        -I$(CIRCLESTDLIBHOME)/include \
                        -Iinclude \
                        -I.

# Experimental Gearmulator SC-88 bare-metal core
SC88HOME := $(CURDIR)/external/gearmulator-sc88
SC88BUILDDIR := $(CURDIR)/build-gearmulator-sc88
SC88LIB := $(SC88BUILDDIR)/libgearmulator_sc88_core.a
INCLUDE += -I$(SC88HOME)/sc88-headless-core

$(SC88LIB): build-gearmulator-sc88-core-pi4.sh
	./build-gearmulator-sc88-core-pi4.sh

EXTRALIBS += --whole-archive $(SC88LIB) --no-whole-archive

# Force keeping the SC-88 link probe when --gc-sections is enabled
LDFLAGS += -u SC88_LinkProbe

# Experimental Nuked-SC55 headless core
SC55LIB := $(CURDIR)/build-sc55/libnukedsc55_core.a

$(SC55LIB): build-nuked-sc55-core-pi4-ofast-cycles24.sh
	./build-nuked-sc55-core-pi4-ofast-cycles24.sh

EXTRALIBS += --whole-archive $(SC55LIB) --no-whole-archive

# Force keeping experimental SC-55 link probe when --gc-sections is enabled
LDFLAGS += -u SC55_LinkProbe
